/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pppppppppppppppppppp
 */
public class ACCOUNTANT_LOGIN extends javax.swing.JPanel {

    /**
     * Creates new form ACCOUNTANT_LOGIN
     */
    public ACCOUNTANT_LOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p51 = new javax.swing.JPanel();
        p52 = new javax.swing.JPanel();
        l51 = new javax.swing.JLabel();
        b52 = new javax.swing.JButton();
        p53 = new javax.swing.JPanel();
        l52 = new javax.swing.JLabel();
        l53 = new javax.swing.JLabel();
        pf51 = new javax.swing.JPasswordField();
        tf51 = new javax.swing.JTextField();
        b51 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        p51.setBackground(new java.awt.Color(153, 153, 153));

        p52.setBackground(new java.awt.Color(255, 153, 153));
        p52.setBorder(new javax.swing.border.MatteBorder(null));

        l51.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        l51.setForeground(new java.awt.Color(102, 0, 0));
        l51.setText("ACCOUNTANT LOGIN");

        b52.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        b52.setForeground(new java.awt.Color(102, 102, 0));
        b52.setText("BACK");

        javax.swing.GroupLayout p52Layout = new javax.swing.GroupLayout(p52);
        p52.setLayout(p52Layout);
        p52Layout.setHorizontalGroup(
            p52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p52Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b52, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(l51, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
        );
        p52Layout.setVerticalGroup(
            p52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p52Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(l51, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(p52Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b52)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p53.setBackground(new java.awt.Color(153, 204, 255));
        p53.setBorder(new javax.swing.border.MatteBorder(null));

        l52.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        l52.setText("NAME :");

        l53.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        l53.setText("PASSWORD :");

        pf51.setBackground(new java.awt.Color(204, 204, 255));
        pf51.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N

        tf51.setBackground(new java.awt.Color(204, 204, 255));
        tf51.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        tf51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf51ActionPerformed(evt);
            }
        });

        b51.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        b51.setForeground(new java.awt.Color(51, 51, 0));
        b51.setText("ENTER TO WORKBOARD");

        javax.swing.GroupLayout p53Layout = new javax.swing.GroupLayout(p53);
        p53.setLayout(p53Layout);
        p53Layout.setHorizontalGroup(
            p53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p53Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(p53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l53, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l52, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(p53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pf51)
                    .addComponent(tf51, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p53Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b51, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );
        p53Layout.setVerticalGroup(
            p53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p53Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(p53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l52, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(tf51))
                .addGap(57, 57, 57)
                .addGroup(p53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l53, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pf51, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(b51, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout p51Layout = new javax.swing.GroupLayout(p51);
        p51.setLayout(p51Layout);
        p51Layout.setHorizontalGroup(
            p51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(p53, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p51Layout.setVerticalGroup(
            p51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p51Layout.createSequentialGroup()
                .addComponent(p52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(p51, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tf51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf51ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b51;
    private javax.swing.JButton b52;
    private javax.swing.JLabel l51;
    private javax.swing.JLabel l52;
    private javax.swing.JLabel l53;
    private javax.swing.JPanel p51;
    private javax.swing.JPanel p52;
    private javax.swing.JPanel p53;
    private javax.swing.JPasswordField pf51;
    private javax.swing.JTextField tf51;
    // End of variables declaration//GEN-END:variables
}
