/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pppppppppppppppppppp
 */
public class ACCOUNTANT_SECTION extends javax.swing.JPanel {

    /**
     * Creates new form ACCOUNTANT_SECTION
     */
    public ACCOUNTANT_SECTION() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p61 = new javax.swing.JPanel();
        p62 = new javax.swing.JPanel();
        l61 = new javax.swing.JLabel();
        p63 = new javax.swing.JPanel();
        b61 = new javax.swing.JButton();
        b62 = new javax.swing.JButton();
        b63 = new javax.swing.JButton();
        b64 = new javax.swing.JButton();
        b65 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        p61.setBackground(new java.awt.Color(153, 153, 153));
        p61.setBorder(new javax.swing.border.MatteBorder(null));

        p62.setBackground(new java.awt.Color(255, 153, 153));

        l61.setBackground(new java.awt.Color(102, 102, 0));
        l61.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        l61.setForeground(new java.awt.Color(153, 0, 0));
        l61.setText("ACCOUNTANT SECTION");

        javax.swing.GroupLayout p62Layout = new javax.swing.GroupLayout(p62);
        p62.setLayout(p62Layout);
        p62Layout.setHorizontalGroup(
            p62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p62Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(l61, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p62Layout.setVerticalGroup(
            p62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p62Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l61, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        p63.setBackground(new java.awt.Color(153, 153, 255));

        b61.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        b61.setForeground(new java.awt.Color(0, 102, 102));
        b61.setText("ADD STUDENT");

        b62.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        b62.setForeground(new java.awt.Color(102, 0, 102));
        b62.setText("VIEW STUDENT");
        b62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b62ActionPerformed(evt);
            }
        });

        b63.setBackground(new java.awt.Color(0, 153, 153));
        b63.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        b63.setForeground(new java.awt.Color(0, 51, 51));
        b63.setText("EDIT STUDENT");

        b64.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        b64.setForeground(new java.awt.Color(153, 0, 51));
        b64.setText("DUE FEE");

        b65.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        b65.setForeground(new java.awt.Color(102, 0, 51));
        b65.setText("LOG-OUT");
        b65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b65ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p63Layout = new javax.swing.GroupLayout(p63);
        p63.setLayout(p63Layout);
        p63Layout.setHorizontalGroup(
            p63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p63Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(p63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b61, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b63, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addGroup(p63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b62, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p63Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b65, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
        );
        p63Layout.setVerticalGroup(
            p63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p63Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(p63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b61, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b62, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(p63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b63, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b64, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(b65, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout p61Layout = new javax.swing.GroupLayout(p61);
        p61.setLayout(p61Layout);
        p61Layout.setHorizontalGroup(
            p61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(p63, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p61Layout.setVerticalGroup(
            p61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p61Layout.createSequentialGroup()
                .addComponent(p62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(p61, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void b62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b62ActionPerformed

    private void b65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b65ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b61;
    private javax.swing.JButton b62;
    private javax.swing.JButton b63;
    private javax.swing.JButton b64;
    private javax.swing.JButton b65;
    private javax.swing.JLabel l61;
    private javax.swing.JPanel p61;
    private javax.swing.JPanel p62;
    private javax.swing.JPanel p63;
    // End of variables declaration//GEN-END:variables
}
