/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pppppppppppppppppppp
 */
public class ADD_STUDENT extends javax.swing.JPanel {

    /**
     * Creates new form ADD_STUDENT
     */
    public ADD_STUDENT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        p71 = new javax.swing.JPanel();
        p72 = new javax.swing.JPanel();
        l71 = new javax.swing.JLabel();
        b71 = new javax.swing.JButton();
        p73 = new javax.swing.JPanel();
        l72 = new javax.swing.JLabel();
        l73 = new javax.swing.JLabel();
        l74 = new javax.swing.JLabel();
        l75 = new javax.swing.JLabel();
        l76 = new javax.swing.JLabel();
        l77 = new javax.swing.JLabel();
        l78 = new javax.swing.JLabel();
        l79 = new javax.swing.JLabel();
        l710 = new javax.swing.JLabel();
        l711 = new javax.swing.JLabel();
        l712 = new javax.swing.JLabel();
        l713 = new javax.swing.JLabel();
        b72 = new javax.swing.JButton();
        tf71 = new javax.swing.JTextField();
        tf72 = new javax.swing.JTextField();
        cb71 = new javax.swing.JComboBox<>();
        tf73 = new javax.swing.JTextField();
        tf74 = new javax.swing.JTextField();
        tf75 = new javax.swing.JTextField();
        tf76 = new javax.swing.JTextField();
        tf77 = new javax.swing.JTextField();
        ta71 = new javax.swing.JScrollPane();
        ta72 = new javax.swing.JTextArea();
        tf79 = new javax.swing.JTextField();
        tf710 = new javax.swing.JTextField();
        cb72 = new javax.swing.JComboBox<>();

        jLabel1.setText("jLabel1");

        setLayout(new java.awt.CardLayout());

        p71.setBackground(new java.awt.Color(153, 153, 153));
        p71.setBorder(new javax.swing.border.MatteBorder(null));

        p72.setBackground(new java.awt.Color(255, 153, 153));

        l71.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        l71.setForeground(new java.awt.Color(153, 102, 0));
        l71.setText("ADD STUDENT");

        b71.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        b71.setForeground(new java.awt.Color(0, 102, 102));
        b71.setText("BACK");
        b71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b71ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p72Layout = new javax.swing.GroupLayout(p72);
        p72.setLayout(p72Layout);
        p72Layout.setHorizontalGroup(
            p72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p72Layout.createSequentialGroup()
                .addComponent(b71, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addComponent(l71, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p72Layout.setVerticalGroup(
            p72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p72Layout.createSequentialGroup()
                .addComponent(b71, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(p72Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(l71, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        p73.setBackground(new java.awt.Color(153, 153, 255));

        l72.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l72.setText("NAME :");

        l73.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l73.setText("E-MAIL :");

        l74.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l74.setText("COURSE :");

        l75.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l75.setText("TOTAL FEE :");

        l76.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l76.setText("FEES PAID :");

        l77.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l77.setText("DATE OF FEE PAID :");

        l78.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l78.setText("DUE FEES : ");

        l79.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l79.setText("ADDRESS :");

        l710.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l710.setText("ROLL NO :");

        l711.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l711.setText("CONTACT NO : ");

        l712.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l712.setText("MODE OF PAYMENT :");

        l713.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        l713.setForeground(new java.awt.Color(102, 0, 0));
        l713.setText("IMPORTANT : FINE FOR LATE FEE IS Rs. 10/DAY...");

        b72.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        b72.setForeground(new java.awt.Color(102, 0, 102));
        b72.setText("ADD STUDENT ");
        b72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b72ActionPerformed(evt);
            }
        });

        tf71.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tf71.setForeground(new java.awt.Color(102, 102, 0));

        tf72.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tf72.setForeground(new java.awt.Color(102, 102, 0));

        cb71.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        cb71.setForeground(new java.awt.Color(102, 102, 0));
        cb71.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bachelor In Technology", "Bachelor In Pharmacy", "Bachelor In Computer Application", "Bachelor In Science", "Bachelor In Commerce", "Bachelor In Commerce (Hons.)", "Hotel Management", "LLB", "MBA", " " }));
        cb71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb71ActionPerformed(evt);
            }
        });

        tf73.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tf73.setForeground(new java.awt.Color(102, 102, 0));

        tf74.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tf74.setForeground(new java.awt.Color(102, 102, 0));
        tf74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf74ActionPerformed(evt);
            }
        });

        tf75.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tf75.setForeground(new java.awt.Color(102, 102, 0));

        tf76.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tf76.setForeground(new java.awt.Color(102, 102, 0));

        tf77.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tf77.setForeground(new java.awt.Color(102, 102, 0));
        tf77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf77ActionPerformed(evt);
            }
        });

        ta72.setColumns(20);
        ta72.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        ta72.setForeground(new java.awt.Color(102, 102, 0));
        ta72.setRows(5);
        ta71.setViewportView(ta72);

        tf79.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tf79.setForeground(new java.awt.Color(102, 102, 0));

        tf710.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tf710.setForeground(new java.awt.Color(102, 102, 0));
        tf710.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf710ActionPerformed(evt);
            }
        });

        cb72.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        cb72.setForeground(new java.awt.Color(102, 102, 0));
        cb72.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "CHEQUE", "DEMAND DRAFT (DD)", "NEFT", "ONLINE TRANSACTION" }));

        javax.swing.GroupLayout p73Layout = new javax.swing.GroupLayout(p73);
        p73.setLayout(p73Layout);
        p73Layout.setHorizontalGroup(
            p73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p73Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(p73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l77, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l76, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l75, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l78, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l79, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l710, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l711, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l712, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(p73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf77)
                    .addComponent(tf75)
                    .addComponent(tf74)
                    .addComponent(tf71)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p73Layout.createSequentialGroup()
                        .addComponent(cb71, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(tf72, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf73)
                    .addComponent(tf76)
                    .addComponent(ta71)
                    .addComponent(tf79)
                    .addComponent(tf710)
                    .addComponent(cb72, 0, 399, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(p73Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l713, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p73Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(b72, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p73Layout.setVerticalGroup(
            p73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p73Layout.createSequentialGroup()
                .addGroup(p73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p73Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(l72, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(p73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf71, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(l73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tf72, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cb71, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(l74, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(p73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf73)
                            .addComponent(l75, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(p73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf74)
                            .addComponent(l76, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(p73Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tf75, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204)))
                .addGroup(p73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p73Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(l77, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf76, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(p73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf77, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l78, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(p73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ta71, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(l79, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(p73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l710, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf79, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(p73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p73Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(tf710, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p73Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l711, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(p73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb72, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l712, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(l713, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b72, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout p71Layout = new javax.swing.GroupLayout(p71);
        p71.setLayout(p71Layout);
        p71Layout.setHorizontalGroup(
            p71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(p73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p71Layout.setVerticalGroup(
            p71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p71Layout.createSequentialGroup()
                .addComponent(p72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(p71, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void b72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b72ActionPerformed

    private void b71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b71ActionPerformed

    private void cb71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb71ActionPerformed

    private void tf74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf74ActionPerformed

    private void tf77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf77ActionPerformed

    private void tf710ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf710ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf710ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b71;
    private javax.swing.JButton b72;
    private javax.swing.JComboBox<String> cb71;
    private javax.swing.JComboBox<String> cb72;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l71;
    private javax.swing.JLabel l710;
    private javax.swing.JLabel l711;
    private javax.swing.JLabel l712;
    private javax.swing.JLabel l713;
    private javax.swing.JLabel l72;
    private javax.swing.JLabel l73;
    private javax.swing.JLabel l74;
    private javax.swing.JLabel l75;
    private javax.swing.JLabel l76;
    private javax.swing.JLabel l77;
    private javax.swing.JLabel l78;
    private javax.swing.JLabel l79;
    private javax.swing.JPanel p71;
    private javax.swing.JPanel p72;
    private javax.swing.JPanel p73;
    private javax.swing.JScrollPane ta71;
    private javax.swing.JTextArea ta72;
    private javax.swing.JTextField tf71;
    private javax.swing.JTextField tf710;
    private javax.swing.JTextField tf72;
    private javax.swing.JTextField tf73;
    private javax.swing.JTextField tf74;
    private javax.swing.JTextField tf75;
    private javax.swing.JTextField tf76;
    private javax.swing.JTextField tf77;
    private javax.swing.JTextField tf79;
    // End of variables declaration//GEN-END:variables
}
