/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pppppppppppppppppppp
 */
public class ADD_ACCOUNTANT extends javax.swing.JPanel {

    /**
     * Creates new form ADD_ACCOUNTANT
     */
    public ADD_ACCOUNTANT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p41 = new javax.swing.JPanel();
        p42 = new javax.swing.JPanel();
        l41 = new javax.swing.JLabel();
        b42 = new javax.swing.JButton();
        p43 = new javax.swing.JPanel();
        l42 = new javax.swing.JLabel();
        l43 = new javax.swing.JLabel();
        l44 = new javax.swing.JLabel();
        l45 = new javax.swing.JLabel();
        tf41 = new javax.swing.JTextField();
        tf43 = new javax.swing.JTextField();
        tf42 = new javax.swing.JTextField();
        pf41 = new javax.swing.JPasswordField();
        b41 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        p41.setBackground(new java.awt.Color(153, 153, 153));

        p42.setBackground(new java.awt.Color(255, 204, 204));
        p42.setBorder(new javax.swing.border.MatteBorder(null));

        l41.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        l41.setForeground(new java.awt.Color(153, 0, 0));
        l41.setText("ADD  ACCOUNTANT");

        b42.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        b42.setForeground(new java.awt.Color(102, 0, 51));
        b42.setText("BACK");

        javax.swing.GroupLayout p42Layout = new javax.swing.GroupLayout(p42);
        p42.setLayout(p42Layout);
        p42Layout.setHorizontalGroup(
            p42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p42Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b42, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145)
                .addComponent(l41, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        p42Layout.setVerticalGroup(
            p42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p42Layout.createSequentialGroup()
                .addGroup(p42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p42Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(l41, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p42Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b42, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        p43.setBackground(new java.awt.Color(153, 204, 255));
        p43.setBorder(new javax.swing.border.MatteBorder(null));

        l42.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        l42.setText("NAME :");

        l43.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        l43.setText("PASSWORD :");

        l44.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        l44.setText("EMAIL - ID :");

        l45.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        l45.setText("CONTACT - NO:");

        tf41.setBackground(new java.awt.Color(204, 204, 255));
        tf41.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        tf41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf41ActionPerformed(evt);
            }
        });

        tf43.setBackground(new java.awt.Color(204, 204, 255));
        tf43.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N

        tf42.setBackground(new java.awt.Color(204, 204, 255));
        tf42.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        tf42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf42ActionPerformed(evt);
            }
        });

        pf41.setBackground(new java.awt.Color(204, 204, 255));
        pf41.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        pf41.setForeground(new java.awt.Color(255, 204, 255));

        b41.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        b41.setForeground(new java.awt.Color(153, 0, 153));
        b41.setText("ADD ACCOUNTANT");

        javax.swing.GroupLayout p43Layout = new javax.swing.GroupLayout(p43);
        p43.setLayout(p43Layout);
        p43Layout.setHorizontalGroup(
            p43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p43Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(p43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l45, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(l44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62)
                .addGroup(p43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf41, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(tf43)
                    .addComponent(tf42)
                    .addComponent(pf41))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p43Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b41, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        p43Layout.setVerticalGroup(
            p43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p43Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(p43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf41)
                    .addComponent(l42, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(p43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l43, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pf41, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(p43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p43Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(l44, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p43Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(tf42, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(p43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf43)
                    .addComponent(l45, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(b41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout p41Layout = new javax.swing.GroupLayout(p41);
        p41.setLayout(p41Layout);
        p41Layout.setHorizontalGroup(
            p41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(p43, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p41Layout.setVerticalGroup(
            p41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p41Layout.createSequentialGroup()
                .addComponent(p42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(p41, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tf42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf42ActionPerformed

    private void tf41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf41ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b41;
    private javax.swing.JButton b42;
    private javax.swing.JLabel l41;
    private javax.swing.JLabel l42;
    private javax.swing.JLabel l43;
    private javax.swing.JLabel l44;
    private javax.swing.JLabel l45;
    private javax.swing.JPanel p41;
    private javax.swing.JPanel p42;
    private javax.swing.JPanel p43;
    private javax.swing.JPasswordField pf41;
    private javax.swing.JTextField tf41;
    private javax.swing.JTextField tf42;
    private javax.swing.JTextField tf43;
    // End of variables declaration//GEN-END:variables
}
