/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pppppppppppppppppppp
 */
public class STUDENT_RECORD extends javax.swing.JPanel {

    /**
     * Creates new form STUDENT_RECORD
     */
    public STUDENT_RECORD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p81 = new javax.swing.JPanel();
        p82 = new javax.swing.JPanel();
        l81 = new javax.swing.JLabel();
        b81 = new javax.swing.JButton();
        p83 = new javax.swing.JPanel();
        l82 = new javax.swing.JLabel();
        l83 = new javax.swing.JLabel();
        l84 = new javax.swing.JLabel();
        l85 = new javax.swing.JLabel();
        l86 = new javax.swing.JLabel();
        l87 = new javax.swing.JLabel();
        l88 = new javax.swing.JLabel();
        l89 = new javax.swing.JLabel();
        l810 = new javax.swing.JLabel();
        l811 = new javax.swing.JLabel();
        tf81 = new javax.swing.JTextField();
        tf82 = new javax.swing.JTextField();
        cb81 = new javax.swing.JComboBox<>();
        tf83 = new javax.swing.JTextField();
        tf84 = new javax.swing.JTextField();
        tf85 = new javax.swing.JTextField();
        tf86 = new javax.swing.JTextField();
        tf87 = new javax.swing.JTextField();
        ta81 = new javax.swing.JScrollPane();
        ta82 = new javax.swing.JTextArea();
        tf88 = new javax.swing.JTextField();
        cb82 = new javax.swing.JComboBox<>();
        l812 = new javax.swing.JLabel();
        tf89 = new javax.swing.JTextField();
        b82 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        p81.setBackground(new java.awt.Color(153, 153, 153));

        p82.setBackground(new java.awt.Color(255, 153, 153));

        l81.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        l81.setForeground(new java.awt.Color(153, 102, 0));
        l81.setText("ADD STUDENT");

        b81.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        b81.setForeground(new java.awt.Color(0, 102, 102));
        b81.setText("BACK");
        b81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b81ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p82Layout = new javax.swing.GroupLayout(p82);
        p82.setLayout(p82Layout);
        p82Layout.setHorizontalGroup(
            p82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p82Layout.createSequentialGroup()
                .addComponent(b81, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addComponent(l81, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        p82Layout.setVerticalGroup(
            p82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p82Layout.createSequentialGroup()
                .addComponent(b81, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(p82Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(l81, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        p83.setBackground(new java.awt.Color(153, 153, 255));

        l82.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l82.setText("NAME :");

        l83.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l83.setText("E-MAIL :");

        l84.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l84.setText("COURSE :");

        l85.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l85.setText("TOTAL FEE :");

        l86.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l86.setText("FEES PAID :");

        l87.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l87.setText("DATE OF FEE PAID :");

        l88.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l88.setText("DUE FEES : ");

        l89.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l89.setText("ADDRESS :");

        l810.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l810.setText("CONTACT NO : ");

        l811.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l811.setText("MODE OF PAYMENT :");

        tf81.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tf81.setForeground(new java.awt.Color(102, 102, 0));

        tf82.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        tf82.setForeground(new java.awt.Color(102, 102, 0));

        cb81.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        cb81.setForeground(new java.awt.Color(102, 102, 0));
        cb81.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bachelor In Technology", "Bachelor In Pharmacy", "Bachelor In Computer Application", "Bachelor In Science", "Bachelor In Commerce", "Bachelor In Commerce (Hons.)", "Hotel Management", "LLB", "MBA", " " }));
        cb81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb81ActionPerformed(evt);
            }
        });

        tf83.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tf83.setForeground(new java.awt.Color(102, 102, 0));
        tf83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf83ActionPerformed(evt);
            }
        });

        tf84.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tf84.setForeground(new java.awt.Color(102, 102, 0));
        tf84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf84ActionPerformed(evt);
            }
        });

        tf85.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tf85.setForeground(new java.awt.Color(102, 102, 0));

        tf86.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tf86.setForeground(new java.awt.Color(102, 102, 0));
        tf86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf86ActionPerformed(evt);
            }
        });

        tf87.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tf87.setForeground(new java.awt.Color(102, 102, 0));
        tf87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf87ActionPerformed(evt);
            }
        });

        ta82.setColumns(20);
        ta82.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        ta82.setForeground(new java.awt.Color(102, 102, 0));
        ta82.setRows(5);
        ta81.setViewportView(ta82);

        tf88.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tf88.setForeground(new java.awt.Color(102, 102, 0));
        tf88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf88ActionPerformed(evt);
            }
        });

        cb82.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        cb82.setForeground(new java.awt.Color(102, 102, 0));
        cb82.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "CHEQUE", "DEMAND DRAFT (DD)", "NEFT", "NET BANKING", " " }));

        l812.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        l812.setText("ROLL NO. : ");

        tf89.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tf89.setForeground(new java.awt.Color(102, 102, 0));
        tf89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf89ActionPerformed(evt);
            }
        });

        b82.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        b82.setForeground(new java.awt.Color(153, 0, 51));
        b82.setText("LOAD RECORD");

        javax.swing.GroupLayout p83Layout = new javax.swing.GroupLayout(p83);
        p83.setLayout(p83Layout);
        p83Layout.setHorizontalGroup(
            p83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p83Layout.createSequentialGroup()
                .addGroup(p83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p83Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(p83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(l86, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l87, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l85, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l84, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l82, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l812, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l88, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l89, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p83Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(l810, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p83Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(l811, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p83Layout.createSequentialGroup()
                        .addGroup(p83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf87)
                            .addComponent(tf85)
                            .addComponent(tf84)
                            .addComponent(tf81)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p83Layout.createSequentialGroup()
                                .addComponent(cb81, 0, 1, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(tf82, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf83)
                            .addComponent(tf86)
                            .addComponent(ta81, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                            .addComponent(tf88)
                            .addComponent(cb82, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf89))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(p83Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(b82, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        p83Layout.setVerticalGroup(
            p83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p83Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(b82, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(p83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l812, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf89, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(p83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf85, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l82, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(p83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l83, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf81, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb81, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf82, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l84, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(p83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l85, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf83, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(p83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf84, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l86, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(p83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf86, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l87, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(p83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf87, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l88, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(p83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l89, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ta81, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(p83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf88, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l810, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb82, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l811, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout p81Layout = new javax.swing.GroupLayout(p81);
        p81.setLayout(p81Layout);
        p81Layout.setHorizontalGroup(
            p81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p82, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(p83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p81Layout.setVerticalGroup(
            p81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p81Layout.createSequentialGroup()
                .addComponent(p82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        add(p81, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void b81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b81ActionPerformed

    private void cb81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb81ActionPerformed

    private void tf84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf84ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf84ActionPerformed

    private void tf87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf87ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf87ActionPerformed

    private void tf88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf88ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf88ActionPerformed

    private void tf86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf86ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf86ActionPerformed

    private void tf83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf83ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf83ActionPerformed

    private void tf89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf89ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf89ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b81;
    private javax.swing.JButton b82;
    private javax.swing.JComboBox<String> cb81;
    private javax.swing.JComboBox<String> cb82;
    private javax.swing.JLabel l81;
    private javax.swing.JLabel l810;
    private javax.swing.JLabel l811;
    private javax.swing.JLabel l812;
    private javax.swing.JLabel l82;
    private javax.swing.JLabel l83;
    private javax.swing.JLabel l84;
    private javax.swing.JLabel l85;
    private javax.swing.JLabel l86;
    private javax.swing.JLabel l87;
    private javax.swing.JLabel l88;
    private javax.swing.JLabel l89;
    private javax.swing.JPanel p81;
    private javax.swing.JPanel p82;
    private javax.swing.JPanel p83;
    private javax.swing.JScrollPane ta81;
    private javax.swing.JTextArea ta82;
    private javax.swing.JTextField tf81;
    private javax.swing.JTextField tf82;
    private javax.swing.JTextField tf83;
    private javax.swing.JTextField tf84;
    private javax.swing.JTextField tf85;
    private javax.swing.JTextField tf86;
    private javax.swing.JTextField tf87;
    private javax.swing.JTextField tf88;
    private javax.swing.JTextField tf89;
    // End of variables declaration//GEN-END:variables
}
